dataset_name: japanese_style

input_dir: data/processed/japanese_style

output_dir: outputs/images

cyclegan_repo: external/pytorch-CycleGAN-and-pix2pix

model_name: style_ukiyoe_pretrained

image_size: 256
batch_size: 1
num_samples: 10

device: cpu

epochs: 100

learning_rate: 0.0002
